export default {
  id: 'operation-glasshouse-s2',
  title: 'Operation Glasshouse',
  subtitle: 'Session 2: Exposure',
  
  duration: 3600, // 60 minutes in seconds
  startTime: { hour: 8, minute: 0 }, // Session starts at 8:00am in-game (Tuesday)
  tokens: 12,
  
  company: {
    name: 'XYZ Pay',
    industry: 'Buy Now Pay Later (BNPL)',
    location: 'Adelaide, Australia',
    employees: 150
  },
  
  briefing: {
    title: 'Incident Response — Day 2',
    date: 'Tuesday, 15 October 2024',
    shift: 'Day Shift (08:00 - 16:00 ACDT)',
    content: `You are the SOC team at XYZ Pay. Yesterday, you uncovered a serious account compromise - an attacker used a staff member's stolen credentials to access 2,847 customer transaction records.

James Okoro (Tier 3 SOC Analyst) worked late to complete a Customer Impact Assessment identifying the affected customers. Marcus (CISO) has called an early briefing.

Your job today: investigate the full scope of the breach, respond to new developments as they arise, and prepare a recommendation for the CISO before his emergency board meeting.

You have 12 action tokens. The clock is ticking. Multiple crises will compete for your attention. You cannot investigate everything. Prioritise wisely.

All names, domain names, locations and IP addresses are fictional. Use the in-game tools to investigate them, not publicly available sources.

Good luck. You're going to need it.`
  },
  
  sessionEnd: {
    title: 'Session Complete',
    message: 'The timer has ended.',
    downloadWarning: 'You must save your session report now. It will not be available to download later.',
    instructions: 'Follow any instructions from your tutor regarding next steps and submission of your report.'
  },
  
  credits: {
    story: 'Story by Tim Churchward and Claude Opus 4.6',
    acknowledgements: 'Thanks to Olaf Maennel and Stephen Hindle',
    assets: 'Profile pictures generated by thispersondoesnotexist.com and thispersondoesnotexist.org using StyleGAN.',
    disclaimer: 'This scenario is entirely fictional. All characters, companies, events, and incidents depicted are products of the imagination. Any resemblance to actual people, companies or events is purely coincidental and unintentional.'
  }
}
