// Session 2 threat intelligence
// Includes Session 1 IPs plus new attacker IPs for David and Nadia compromises

export default {
  ips: {
    '103.42.91.17': {
      type: 'ip',
      reputation: 'malicious',
      riskScore: 95,
      category: 'VPN/Proxy Service',
      country: 'Indonesia',
      asn: 'AS136052 - PT Cloud Hosting Indonesia',
      firstSeen: '2024-09-15',
      lastSeen: '2024-10-14',
      tags: ['vpn', 'proxy', 'anonymisation', 'known-attacker'],
      reports: 23,
      summary: 'Commercial VPN endpoint in Indonesia. Associated with account compromise of liam.fitzgerald and failed MFA attempt on anika.patel. BLOCKED at perimeter firewall as of Monday 11:30.',
      relatedCampaigns: ['IR-2024-0847'],
      recommendation: 'Already blocked. Monitor for related IPs from same provider.',
      actions: []
    },
    '185.220.101.48': {
      type: 'ip',
      reputation: 'suspicious',
      riskScore: 70,
      category: 'VPN/Proxy Service',
      country: 'Netherlands',
      asn: 'AS60729 - Stichting ZAVOD',
      firstSeen: '2024-10-01',
      lastSeen: '2024-10-13',
      tags: ['vpn', 'proxy', 'tor-adjacent'],
      reports: 12,
      summary: 'European VPN endpoint associated with privacy-focused hosting. Single brief login to nadia.khoury account on Sunday 09:15. No further activity.',
      relatedCampaigns: [],
      recommendation: 'Investigate connection to IR-2024-0847. Consider blocking.',
      actions: []
    },
    '198.54.131.152': {
      type: 'ip',
      reputation: 'suspicious',
      riskScore: 55,
      category: 'VPN/Proxy Service',
      country: 'United States',
      asn: 'AS22612 - Namecheap Inc',
      firstSeen: '2024-10-05',
      lastSeen: '2024-10-12',
      tags: ['vpn', 'hosting', 'commercial'],
      reports: 8,
      summary: 'US-based commercial VPN/hosting endpoint. Single brief login to david.chen account on Saturday 14:23. No further activity.',
      relatedCampaigns: [],
      recommendation: 'Investigate connection to IR-2024-0847. Consider blocking.',
      actions: []
    },
    '172.104.191.33': {
      type: 'ip',
      reputation: 'suspicious',
      riskScore: 50,
      category: 'VPN/Proxy Service',
      country: 'Japan',
      asn: 'AS63949 - Akamai Connected Cloud (Linode)',
      firstSeen: '2024-10-08',
      lastSeen: '2024-10-12',
      tags: ['vpn', 'cloud-hosting', 'commercial'],
      reports: 5,
      summary: 'Japanese cloud hosting endpoint (Linode). Single brief login to tom.bradshaw account on Saturday 10:47. No further activity.',
      relatedCampaigns: [],
      recommendation: 'Investigate connection to IR-2024-0847. Consider blocking.',
      actions: []
    },
    '103.2.117.8': {
      type: 'ip',
      reputation: 'clean',
      riskScore: 15,
      category: 'Commercial ISP',
      country: 'Australia',
      asn: 'AS10143 - Superloop Ltd',
      firstSeen: '2024-10-07',
      lastSeen: '2024-10-15',
      tags: ['isp', 'commercial', 'residential-business'],
      reports: 0,
      summary: 'Adelaide-based Superloop commercial internet. Commonly used for business and residential broadband in South Australia. No threat reports.',
      relatedCampaigns: [],
      recommendation: 'Clean. No action unless correlated with suspicious activity from an unexpected user or device.',
      actions: []
    },
    // Tor exit nodes from credential stuffing (carried over from Session 1)
    '185.220.101.42': {
      type: 'ip',
      reputation: 'malicious',
      riskScore: 85,
      category: 'Tor Exit Node',
      country: 'Germany',
      asn: 'AS60729 - Stichting ZAVOD',
      firstSeen: '2024-06-12',
      lastSeen: '2024-10-15',
      tags: ['tor', 'credential-stuffing', 'botnet'],
      reports: 156,
      summary: 'Known Tor exit node. Frequent source of credential stuffing against AU financial services. Ongoing automated attacks, not believed to be related to targeted IR-2024-0847 campaign.',
      relatedCampaigns: [],
      recommendation: 'Rate limiting in place. Background noise — low priority.',
      actions: []
    },
    '91.240.118.29': {
      type: 'ip',
      reputation: 'malicious',
      riskScore: 80,
      category: 'Tor Exit Node',
      country: 'Romania',
      asn: 'AS9009 - M247 Ltd',
      firstSeen: '2024-08-03',
      lastSeen: '2024-10-15',
      tags: ['tor', 'credential-stuffing', 'botnet'],
      reports: 89,
      summary: 'Known Tor exit node. Source of ongoing credential stuffing. Background noise.',
      relatedCampaigns: [],
      recommendation: 'Rate limiting in place. Background noise — low priority.',
      actions: []
    },
    '194.26.192.71': {
      type: 'ip',
      reputation: 'malicious',
      riskScore: 75,
      category: 'Tor Exit Node',
      country: 'Latvia',
      asn: 'AS52000 - AEZA GROUP Ltd',
      firstSeen: '2024-09-20',
      lastSeen: '2024-10-15',
      tags: ['tor', 'credential-stuffing'],
      reports: 34,
      summary: 'Tor exit node. Source of credential stuffing attempts. Background noise.',
      relatedCampaigns: [],
      recommendation: 'Rate limiting in place. Background noise — low priority.',
      actions: []
    }
  },
  domains: {},
  hashes: {},
  emails: {}
}
